name: Training
description: $description
version: '${version}'

main: net.nightgamer.Training
api-version: '1.21.1'
load: STARTUP

authors: [ NightGamer ]

commands:

  lol:

  heal:

  spawn:

  setspawn:

  clearinv:

  fly:

  kill:

  hunger:

  day:

  night:

  flyspeed:

  walkspeed:

  sun:

  rain:

  storm:

  head:

  enderc:

  wb:

  explode:

  location:

  world:

  who:

  players:

  msg:

  reply:
